version: "3"
services:
  product-backend:
    image: sabira9/madhar_backend_app:1.0
    ports:
      - "9090:9090"
    networks:
      - product-management-system
  product-frontend:
    image: sabira9/madhar_frontend_app:1.0
    ports:
      - "80:80"
    depends_on:
      - product-backend
    networks:
      - product-management-system
networks:
  product-management-system:  
